FROM node:19.6
WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY tsconfig.json ./

RUN npm install -g typescript
RUN npm install -g ts-node
RUN yarn install

COPY . .

EXPOSE 4001
CMD ["yarn", "run", "start"]
